### ISSUE TITLE
Accesso non possibile da nessun browser mobile su iOS

### ISSUE THREAD

**Issue by butckhe** [colamonico-chiarulli/smartbreak#3]
Dopo aver provato ad accedere a SmartBreak con Safari su iOS 1.15.2 senza successo, ho tentato di accedere con altri browser (Opera, Firefox, Brave) equamente senza riscontro positivo, re-inoltrandomi alla pagina di login.

**Comment by rino-andriano** [comment]
Non ci sono limiti di piattaforma (Windows, Linux, oOS, Andoid, ecc) - unica condizione è avere un browser qualsiasi ed essere autenticati su Google con l'account istituzionale.
Nel caso di più account Google attivati nel browser - seguire le indicazioni di questo link
https://support.google.com/accounts/answer/1721977?hl=it

Inoltre bisogna verificare di non aver bloccato i cookie di terze parti a livello di sistema e le finestre pop-up
