### ISSUE TITLE
Articoli nel carrello non appaiono in determinate pagine 

### ISSUE THREAD

**Issue by butckhe** [colamonico-chiarulli/smartbreak#4]
[Dopo aver aggiunto articoli al carrello](https://imgur.com/3x1Mpl0), il numero degli articoli e il loro prezzo non appare nelle pagine [Credits](https://imgur.com/aNe2ETQ), [Statistiche](https://imgur.com/E8qYUFF), [Ordini della mia classe](https://imgur.com/UKtxmGR) e [I miei ordini](https://imgur.com/1P49cXQ).

**Comment by rino-andriano** [comment]
Non vedo dov'è l'errore: Tutte le pagine citate, sono pagine che non hanno nulla a che fare con l'ordine. Il numero degli articoli è volutamente visibile solo in "Fai un'ordine"
